name: Build, Export and Publish Next.js App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: |
          yarn install
          yarn build
      - name: Next Pages
        uses: reeseovine/next-pages@v1.0
      - name: Commit and push changes
        run: |
          echo "api.myownfreehost.net" >> docs/CNAME
          git config --global user.name "mofh-docs-builder"
          git config --global user.email "hello@robert-s.dev"
          git add -A
          git commit -m "New Build"
          git push
